Repository ROBOTIS-GIT/open_manipulator, pull requests merged in 2025-06, with the labels that each got.

#296 Update dependancy
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/CMakeLists.txt
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/CMakeLists.txt
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/CMakeLists.txt
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_gravity_compensation_controller/src/gravity_compensation_controller.cpp
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/CMakeLists.txt
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/src/joint_trajectory_command_broadcaster.cpp
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/CMakeLists.txt
  ros2_controller/om_spring_actuator_controller/include/spring_actuator_controller/spring_actuator_controller.hpp
  ros2_controller/om_spring_actuator_controller/package.xml
  ros2_controller/om_spring_actuator_controller/src/spring_actuator_controller.cpp
Labels: enhancement

#317 Update Docker configurations and hotfix for OMY init position parameters
  docker/Dockerfile
  docker/container.sh
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/launch/omy_3m.launch.py
  open_manipulator_bringup/launch/omy_f3m.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
Labels: enhancement, bug

#318 Bump 4.0.2
  docker/Dockerfile
  docker/container.sh
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/launch/omy_3m.launch.py
  open_manipulator_bringup/launch/omy_f3m.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
Labels: bump

#322 Bump 4.0.4
  docker/container.sh
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/CHANGELOG.rst
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
Labels: bump
