Repository ROBOTIS-GIT/open_manipulator, pull requests merged in 2025-07, with the labels that each got.

#324 Update for OMY profile and dynamic init_position config file selection
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/config/omy_3m/qc_positions.yaml
  open_manipulator_bringup/config/omy_f3m_follower_ai/qc_positions.yaml
  open_manipulator_bringup/config/omy_l100_leader_ai/hardware_controller_manager.yaml
  open_manipulator_bringup/launch/omx.launch.py
  open_manipulator_bringup/launch/omy_3m.launch.py
  open_manipulator_bringup/launch/omy_f3m.launch.py
  open_manipulator_bringup/launch/omy_f3m_follower_ai.launch.py
  open_manipulator_bringup/launch/omy_l100_leader_ai.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/CHANGELOG.rst
  open_manipulator_collision/launch/self_collision.launch.py
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_description/ros2_control/omy_3m.ros2_control.xacro
  open_manipulator_description/ros2_control/omy_f3m.ros2_control.xacro
  open_manipulator_description/urdf/omy_f3m/omy_f3m_arm.urdf.xacro
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/include/gravity_compensation_controller/gravity_compensation_controller.hpp
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_gravity_compensation_controller/src/gravity_compensation_controller.cpp
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/src/joint_trajectory_command_broadcaster.cpp
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
  ros2_controller/om_spring_actuator_controller/src/spring_actuator_controller.cpp
Labels: enhancement

#325 Bump 4.0.5
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/config/omy_3m/qc_positions.yaml
  open_manipulator_bringup/config/omy_f3m_follower_ai/qc_positions.yaml
  open_manipulator_bringup/config/omy_l100_leader_ai/hardware_controller_manager.yaml
  open_manipulator_bringup/launch/omx.launch.py
  open_manipulator_bringup/launch/omy_3m.launch.py
  open_manipulator_bringup/launch/omy_f3m.launch.py
  open_manipulator_bringup/launch/omy_f3m_follower_ai.launch.py
  open_manipulator_bringup/launch/omy_l100_leader_ai.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/CHANGELOG.rst
  open_manipulator_collision/launch/self_collision.launch.py
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/package.xml
  open_manipulator_description/ros2_control/omy_3m.ros2_control.xacro
  open_manipulator_description/ros2_control/omy_f3m.ros2_control.xacro
  open_manipulator_description/urdf/omy_f3m/omy_f3m_arm.urdf.xacro
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/package.xml
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/package.xml
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/include/gravity_compensation_controller/gravity_compensation_controller.hpp
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_gravity_compensation_controller/src/gravity_compensation_controller.cpp
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/src/joint_trajectory_command_broadcaster.cpp
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
  ros2_controller/om_spring_actuator_controller/src/spring_actuator_controller.cpp
Labels: bump

#326 Resolved an issue where simulation models were not loading
  .github/workflows/ros-lint.yml
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_x_bringup/CHANGELOG.rst
  open_manipulator_x_bringup/launch/base.launch.py
  open_manipulator_x_bringup/launch/fake.launch.py
  open_manipulator_x_bringup/launch/gazebo.launch.py
  open_manipulator_x_bringup/launch/hardware.launch.py
  open_manipulator_x_bringup/package.xml
  open_manipulator_x_description/CHANGELOG.rst
  open_manipulator_x_description/launch/model.launch.py
  open_manipulator_x_description/package.xml
  open_manipulator_x_gui/CHANGELOG.rst
  open_manipulator_x_gui/include/open_manipulator_x_gui/main_window.hpp
  open_manipulator_x_gui/include/open_manipulator_x_gui/qnode.hpp
  open_manipulator_x_gui/launch/open_manipulator_x_gui.launch.py
  open_manipulator_x_gui/package.xml
  open_manipulator_x_gui/src/main.cpp
  open_manipulator_x_gui/src/main_window.cpp
  open_manipulator_x_gui/src/qnode.cpp
  open_manipulator_x_moveit_config/CHANGELOG.rst
  open_manipulator_x_moveit_config/launch/demo.launch.py
  open_manipulator_x_moveit_config/launch/move_group.launch.py
  open_manipulator_x_moveit_config/launch/moveit_core.launch.py
  open_manipulator_x_moveit_config/launch/moveit_gazebo.launch.py
  open_manipulator_x_moveit_config/launch/moveit_rviz.launch.py
  open_manipulator_x_moveit_config/launch/rsp.launch.py
  open_manipulator_x_moveit_config/launch/servo.launch.py
  open_manipulator_x_moveit_config/launch/setup_assistant.launch.py
  open_manipulator_x_moveit_config/launch/spawn_controllers.launch.py
  open_manipulator_x_moveit_config/launch/static_virtual_joint_tfs.launch.py
  open_manipulator_x_moveit_config/package.xml
  open_manipulator_x_playground/CHANGELOG.rst
  open_manipulator_x_playground/package.xml
  open_manipulator_x_playground/src/hello_moveit.cpp
  open_manipulator_x_teleop/CHANGELOG.rst
  open_manipulator_x_teleop/include/open_manipulator_x_teleop/open_manipulator_x_teleop.hpp
  open_manipulator_x_teleop/package.xml
  open_manipulator_x_teleop/src/open_manipulator_x_teleop.cpp
Labels: enhancement

#327 Update readme
  README.md
Labels: documentation

#328 Release Error fix
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_x_bringup/CHANGELOG.rst
  open_manipulator_x_bringup/package.xml
  open_manipulator_x_description/CHANGELOG.rst
  open_manipulator_x_description/package.xml
  open_manipulator_x_gui/CHANGELOG.rst
  open_manipulator_x_gui/CMakeLists.txt
  open_manipulator_x_gui/include/open_manipulator_x_gui/main_window.hpp
  open_manipulator_x_gui/package.xml
  open_manipulator_x_moveit_config/CHANGELOG.rst
  open_manipulator_x_moveit_config/package.xml
  open_manipulator_x_playground/CHANGELOG.rst
  open_manipulator_x_playground/package.xml
  open_manipulator_x_teleop/CHANGELOG.rst
  open_manipulator_x_teleop/package.xml
Labels: bug

#329 Rename omx to open_manipulator_x
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/config/open_manipulator_x/hardware_controller_manager.yaml
  open_manipulator_bringup/config/open_manipulator_x/initial_positions.yaml
  open_manipulator_bringup/launch/open_manipulator_x.launch.py
  open_manipulator_bringup/launch/open_manipulator_x_gazebo.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/CHANGELOG.rst
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/gazebo/open_manipulator_x.gazebo.xacro
  open_manipulator_description/launch/open_manipulator_x.launch.py
  open_manipulator_description/meshes/open_manipulator_x/gripper_left_palm.stl
  open_manipulator_description/meshes/open_manipulator_x/gripper_right_palm.stl
  open_manipulator_description/meshes/open_manipulator_x/link1.stl
  open_manipulator_description/meshes/open_manipulator_x/link2.stl
  open_manipulator_description/meshes/open_manipulator_x/link3.stl
  open_manipulator_description/meshes/open_manipulator_x/link4.stl
  open_manipulator_description/meshes/open_manipulator_x/link5.stl
  open_manipulator_description/meshes/open_manipulator_x/plate.stl
  open_manipulator_description/package.xml
  open_manipulator_description/ros2_control/open_manipulator_x.ros2_control.xacro
  open_manipulator_description/urdf/open_manipulator_x/open_manipulator_x.urdf.xacro
  open_manipulator_description/urdf/open_manipulator_x/open_manipulator_x_arm.urdf.xacro
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/CMakeLists.txt
  open_manipulator_gui/config/open_manipulator_x_joint_log.csv
  open_manipulator_gui/include/open_manipulator_x_gui/main_window.hpp
  open_manipulator_gui/include/open_manipulator_x_gui/qnode.hpp
  open_manipulator_gui/launch/open_manipulator_x_gui.launch.py
  open_manipulator_gui/package.xml
  open_manipulator_gui/src/open_manipulator_x/main.cpp
  open_manipulator_gui/src/open_manipulator_x/main_window.cpp
  open_manipulator_gui/src/open_manipulator_x/qnode.cpp
  open_manipulator_gui/ui/open_manipulator_x_main_window.ui
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/config/open_manipulator_x/joint_limits.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/kinematics.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/moveit_controllers.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/open_manipulator_x.srdf
  open_manipulator_moveit_config/launch/open_manipulator_x_moveit.launch.py
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/CMakeLists.txt
  open_manipulator_playground/include/open_manipulator_playground/open_manipulator_x_hello_moveit.h
  open_manipulator_playground/package.xml
  open_manipulator_playground/src/open_manipulator_x_hello_moveit.cpp
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/open_manipulator_teleop/open_manipulator_x_teleop.py
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
Labels: enhancement

#331 Bump 4.0.6
  README.md
  open_manipulator/CHANGELOG.rst
  open_manipulator/package.xml
  open_manipulator_bringup/CHANGELOG.rst
  open_manipulator_bringup/config/open_manipulator_x/hardware_controller_manager.yaml
  open_manipulator_bringup/config/open_manipulator_x/initial_positions.yaml
  open_manipulator_bringup/launch/open_manipulator_x.launch.py
  open_manipulator_bringup/launch/open_manipulator_x_gazebo.launch.py
  open_manipulator_bringup/package.xml
  open_manipulator_bringup/setup.py
  open_manipulator_collision/CHANGELOG.rst
  open_manipulator_collision/package.xml
  open_manipulator_description/CHANGELOG.rst
  open_manipulator_description/gazebo/open_manipulator_x.gazebo.xacro
  open_manipulator_description/launch/open_manipulator_x.launch.py
  open_manipulator_description/meshes/open_manipulator_x/gripper_left_palm.stl
  open_manipulator_description/meshes/open_manipulator_x/gripper_right_palm.stl
  open_manipulator_description/meshes/open_manipulator_x/link1.stl
  open_manipulator_description/meshes/open_manipulator_x/link2.stl
  open_manipulator_description/meshes/open_manipulator_x/link3.stl
  open_manipulator_description/meshes/open_manipulator_x/link4.stl
  open_manipulator_description/meshes/open_manipulator_x/link5.stl
  open_manipulator_description/meshes/open_manipulator_x/plate.stl
  open_manipulator_description/package.xml
  open_manipulator_description/ros2_control/open_manipulator_x.ros2_control.xacro
  open_manipulator_description/urdf/open_manipulator_x/open_manipulator_x.urdf.xacro
  open_manipulator_description/urdf/open_manipulator_x/open_manipulator_x_arm.urdf.xacro
  open_manipulator_gui/CHANGELOG.rst
  open_manipulator_gui/CMakeLists.txt
  open_manipulator_gui/config/open_manipulator_x_joint_log.csv
  open_manipulator_gui/include/open_manipulator_x_gui/main_window.hpp
  open_manipulator_gui/include/open_manipulator_x_gui/qnode.hpp
  open_manipulator_gui/launch/open_manipulator_x_gui.launch.py
  open_manipulator_gui/package.xml
  open_manipulator_gui/src/open_manipulator_x/main.cpp
  open_manipulator_gui/src/open_manipulator_x/main_window.cpp
  open_manipulator_gui/src/open_manipulator_x/qnode.cpp
  open_manipulator_gui/ui/open_manipulator_x_main_window.ui
  open_manipulator_moveit_config/CHANGELOG.rst
  open_manipulator_moveit_config/config/open_manipulator_x/joint_limits.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/kinematics.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/moveit_controllers.yaml
  open_manipulator_moveit_config/config/open_manipulator_x/open_manipulator_x.srdf
  open_manipulator_moveit_config/launch/open_manipulator_x_moveit.launch.py
  open_manipulator_moveit_config/package.xml
  open_manipulator_playground/CHANGELOG.rst
  open_manipulator_playground/CMakeLists.txt
  open_manipulator_playground/include/open_manipulator_playground/open_manipulator_x_hello_moveit.h
  open_manipulator_playground/package.xml
  open_manipulator_playground/src/open_manipulator_x_hello_moveit.cpp
  open_manipulator_teleop/CHANGELOG.rst
  open_manipulator_teleop/open_manipulator_teleop/open_manipulator_x_teleop.py
  open_manipulator_teleop/package.xml
  open_manipulator_teleop/setup.py
  ros2_controller/om_gravity_compensation_controller/CHANGELOG.rst
  ros2_controller/om_gravity_compensation_controller/package.xml
  ros2_controller/om_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ros2_controller/om_joint_trajectory_command_broadcaster/package.xml
  ros2_controller/om_spring_actuator_controller/CHANGELOG.rst
  ros2_controller/om_spring_actuator_controller/package.xml
Labels: bump
